# Site settings
title: Alistair Miles
email: alimanfoo@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Science, data, code, ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alimanfoo
github_username:  alimanfoo

# Build settings
markdown: kramdown
exclude: ['*.ipynb', '*.sh']
